{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ac319d67",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-09-26 12:03:20.328 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:20.337 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-09-26 12:03:20.351 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-09-26 12:03:20.371 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.899 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run c:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-09-26 12:03:23.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.905 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.908 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.917 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.920 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.926 No runtime found, using MemoryCacheStorageManager\n",
      "2025-09-26 12:03:23.930 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.933 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.935 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:23.937 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:24.607 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:24.644 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:24.652 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:25.390 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:25.392 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:25.395 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:25.400 No runtime found, using MemoryCacheStorageManager\n",
      "2025-09-26 12:03:25.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:25.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:25.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:25.632 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.251 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.261 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.266 Thread 'Thread-4': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.531 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.537 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.544 Session state does not function when running a script without `streamlit run`\n",
      "2025-09-26 12:03:26.547 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.557 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.560 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.579 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.612 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.615 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:26.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:27.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.399 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.401 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.404 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.422 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.491 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.495 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.499 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2025-09-26 12:03:29.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:29.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "C:\\Users\\ADMIN\\AppData\\Local\\Temp\\ipykernel_2704\\11195805.py:190: FutureWarning: \n",
      "\n",
      "Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.\n",
      "\n",
      "  sns.barplot(x='Count', y='Journal', data=top_journals, palette='viridis', ax=ax)\n",
      "2025-09-26 12:03:30.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:30.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:30.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:30.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:30.999 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:31.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:31.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:31.029 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:31.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:31.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:31.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:32.273 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.181 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.185 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.189 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.193 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2025-09-26 12:03:34.213 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.215 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.219 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.223 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.235 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.240 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.249 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.292 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.314 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.403 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\streamlit\\dataframe_util.py\", line 822, in convert_pandas_df_to_arrow_bytes\n",
      "    table = pa.Table.from_pandas(df)\n",
      "  File \"pyarrow\\\\table.pxi\", line 4795, in pyarrow.lib.Table.from_pandas\n",
      "  File \"c:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pyarrow\\pandas_compat.py\", line 637, in dataframe_to_arrays\n",
      "    arrays = [convert_column(c, f)\n",
      "              ~~~~~~~~~~~~~~^^^^^^\n",
      "  File \"c:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pyarrow\\pandas_compat.py\", line 625, in convert_column\n",
      "    raise e\n",
      "  File \"c:\\Users\\ADMIN\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pyarrow\\pandas_compat.py\", line 619, in convert_column\n",
      "    result = pa.array(col, type=type_, from_pandas=True, safe=safe)\n",
      "  File \"pyarrow\\\\array.pxi\", line 365, in pyarrow.lib.array\n",
      "  File \"pyarrow\\\\array.pxi\", line 91, in pyarrow.lib._ndarray_to_array\n",
      "  File \"pyarrow\\\\error.pxi\", line 92, in pyarrow.lib.check_status\n",
      "pyarrow.lib.ArrowInvalid: (\"Could not convert dtype('O') with type numpy.dtypes.ObjectDType: did not recognize Python value type when inferring an Arrow data type\", 'Conversion failed for column Data Type with type object')\n",
      "2025-09-26 12:03:34.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.684 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.710 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.719 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.800 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2025-09-26 12:03:34.808 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.812 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.817 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.821 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.826 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:34.839 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.110 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.134 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.139 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.146 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2025-09-26 12:03:35.278 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.286 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-09-26 12:03:35.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import requests\n",
    "import io\n",
    "import re\n",
    "from wordcloud import WordCloud\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from collections import Counter\n",
    "import datetime\n",
    "import os # Import os for file path check\n",
    "\n",
    "# --- Configuration ---\n",
    "# Local file configuration instead of remote URL download\n",
    "LOCAL_FILE_PATH = \"dataset_first_5000.csv\"\n",
    "\n",
    "# Set page configuration for better aesthetics\n",
    "st.set_page_config(layout=\"wide\", page_title=\"CORD-19 Research Analysis\")\n",
    "\n",
    "# --- Part 1: Data Download and Loading (Updated for Local File) ---\n",
    "\n",
    "@st.cache_data(show_spinner=f\"Loading local file: {LOCAL_FILE_PATH}...\")\n",
    "def download_and_load_data(file_path):\n",
    "    \"\"\"\n",
    "    Loads the metadata from a local CSV file into a pandas DataFrame.\n",
    "    Uses caching to avoid re-reading the disk file on every interaction.\n",
    "    \"\"\"\n",
    "    if not os.path.exists(file_path):\n",
    "        st.error(f\"Error: The file '{file_path}' was not found.\")\n",
    "        st.info(\"Please ensure 'dataset_first_5000.csv' is in the same directory as this script.\")\n",
    "        return pd.DataFrame()\n",
    "        \n",
    "    try:\n",
    "        df = pd.read_csv(file_path)\n",
    "        return df\n",
    "    except Exception as e:\n",
    "        st.error(f\"Error loading data from '{file_path}': {e}\")\n",
    "        st.info(\"Check if the file is a valid CSV and not corrupted.\")\n",
    "        return pd.DataFrame()\n",
    "\n",
    "# --- Part 2: Data Cleaning and Preparation ---\n",
    "\n",
    "@st.cache_data(show_spinner=\"Cleaning and preparing data...\")\n",
    "def clean_and_prepare_data(df):\n",
    "    \"\"\"\n",
    "    Performs data cleaning, missing value handling, and feature engineering.\n",
    "    \"\"\"\n",
    "    initial_shape = df.shape\n",
    "\n",
    "    # 1. Handle Missing Data: Focus on essential columns for analysis\n",
    "    # Drop rows where 'title' is missing, as a paper without a title is not useful.\n",
    "    df.dropna(subset=['title'], inplace=True)\n",
    "\n",
    "    # Convert 'publish_time' to datetime. Handle errors by coercing to NaT.\n",
    "    df['publish_time'] = pd.to_datetime(df['publish_time'], errors='coerce')\n",
    "\n",
    "    # Drop rows where 'publish_time' is NaT after conversion\n",
    "    df.dropna(subset=['publish_time'], inplace=True)\n",
    "\n",
    "    # 2. Prepare Data for Analysis\n",
    "    \n",
    "    # Extract publication year\n",
    "    df['publication_year'] = df['publish_time'].dt.year\n",
    "\n",
    "    # Calculate abstract word count (requires abstract to not be NaN)\n",
    "    df['abstract_word_count'] = df['abstract'].fillna('').apply(lambda x: len(x.split()))\n",
    "\n",
    "    # Convert journal names to string and fill NaNs for consistent grouping\n",
    "    df['journal'] = df['journal'].astype(str).str.lower().str.strip().replace('nan', 'Unknown Journal')\n",
    "\n",
    "    # Remove duplicates based on title and abstract (likely the same paper)\n",
    "    df.drop_duplicates(subset=['title', 'abstract'], keep='first', inplace=True)\n",
    "    \n",
    "    st.sidebar.success(f\"Data cleaned. Rows reduced from {initial_shape[0]} to {df.shape[0]}.\")\n",
    "    return df\n",
    "\n",
    "# --- Part 3: Data Analysis Functions ---\n",
    "\n",
    "def analyze_publications_over_time(df):\n",
    "    \"\"\"Count papers by publication year.\"\"\"\n",
    "    yearly_counts = df.groupby('publication_year').size().reset_index(name='Count')\n",
    "    return yearly_counts.sort_values('publication_year', ascending=True)\n",
    "\n",
    "def analyze_top_journals(df, top_n=10):\n",
    "    \"\"\"Identify top journals.\"\"\"\n",
    "    top_journals = df['journal'].value_counts().nlargest(top_n).reset_index()\n",
    "    top_journals.columns = ['Journal', 'Count']\n",
    "    # Filter out the placeholder 'Unknown Journal' for visualization\n",
    "    top_journals = top_journals[top_journals['Journal'] != 'unknown journal']\n",
    "    return top_journals\n",
    "\n",
    "def get_word_frequencies(df, column, top_n=50, remove_stopwords=True):\n",
    "    \"\"\"Find most frequent words in a text column (e.g., title or abstract).\"\"\"\n",
    "    # Combine all text into a single string\n",
    "    text = ' '.join(df[column].dropna().astype(str).str.lower())\n",
    "    \n",
    "    # Simple tokenization (removing punctuation and splitting by space)\n",
    "    words = re.findall(r'\\b\\w+\\b', text)\n",
    "    \n",
    "    if remove_stopwords:\n",
    "        # Simple list of common English stopwords\n",
    "        stopwords = set(st.session_state.get('stopwords', ['the', 'and', 'to', 'of', 'in', 'a', 'is', 'for', 'with', 'on', 'as', 'it', 'from', 'by', 'at', 'that', 'this', 'have', 'are', 'be', 'an', 'or', 'was', 'were']))\n",
    "        words = [word for word in words if word not in stopwords and len(word) > 2]\n",
    "        \n",
    "    word_counts = Counter(words)\n",
    "    return word_counts.most_common(top_n)\n",
    "\n",
    "\n",
    "# --- Streamlit Application Layout and Display ---\n",
    "\n",
    "def main():\n",
    "    \"\"\"The main Streamlit application function.\"\"\"\n",
    "    st.title(\"🔬 CORD-19 Research Metadata Analysis\")\n",
    "    st.markdown(f\"\"\"\n",
    "        An interactive application to explore the CORD-19 metadata, loaded from the local file \n",
    "        `{LOCAL_FILE_PATH}`. This analysis covers publication trends, top journals, and key terms used in paper titles.\n",
    "    \"\"\")\n",
    "    st.divider()\n",
    "    \n",
    "    # 1. Load Data\n",
    "    # Pass the local file path to the loading function\n",
    "    raw_df = download_and_load_data(LOCAL_FILE_PATH)\n",
    "    \n",
    "    if raw_df.empty:\n",
    "        # Stop execution if file is not found or failed to load\n",
    "        st.stop()\n",
    "        \n",
    "    # 2. Clean Data\n",
    "    df = clean_and_prepare_data(raw_df.copy())\n",
    "    \n",
    "    # Initialize session state for analysis parameters (if needed later)\n",
    "    if 'stopwords' not in st.session_state:\n",
    "        st.session_state['stopwords'] = ['the', 'and', 'to', 'of', 'in', 'a', 'is', 'for', 'with', 'on', 'as', 'it', 'from', 'by', 'at', 'that', 'this', 'have', 'are', 'be', 'an', 'or', 'was', 'were']\n",
    "\n",
    "    # --- Sidebar for Filtering/Controls ---\n",
    "    st.sidebar.header(\"Analysis Controls\")\n",
    "    \n",
    "    # Slider for Year Filtering\n",
    "    min_year = int(df['publication_year'].min())\n",
    "    max_year = int(df['publication_year'].max())\n",
    "    year_range = st.sidebar.slider(\n",
    "        \"Select Publication Year Range\",\n",
    "        min_value=min_year,\n",
    "        max_value=max_year,\n",
    "        value=(2019, max_year) \n",
    "    )\n",
    "    \n",
    "    # Apply year filter\n",
    "    filtered_df = df[\n",
    "        (df['publication_year'] >= year_range[0]) & \n",
    "        (df['publication_year'] <= year_range[1])\n",
    "    ]\n",
    "    \n",
    "    st.sidebar.info(f\"Filtered Dataset Size: {filtered_df.shape[0]} papers.\")\n",
    "\n",
    "    if filtered_df.empty:\n",
    "        st.warning(\"No data available for the selected year range.\")\n",
    "        st.stop()\n",
    "\n",
    "\n",
    "    # --- Analysis and Visualization Sections ---\n",
    "\n",
    "    # --- Part 3: Publication Trend over Time ---\n",
    "    st.header(\"1. Publication Trend Over Time\")\n",
    "    \n",
    "    yearly_counts = analyze_publications_over_time(filtered_df)\n",
    "    \n",
    "    fig, ax = plt.subplots(figsize=(10, 5))\n",
    "    sns.lineplot(x='publication_year', y='Count', data=yearly_counts, marker='o', ax=ax)\n",
    "    ax.set_title(f'Number of Papers Published ({year_range[0]}-{year_range[1]})', fontsize=16)\n",
    "    ax.set_xlabel('Publication Year')\n",
    "    ax.set_ylabel('Number of Papers')\n",
    "    ax.grid(True, linestyle='--', alpha=0.6)\n",
    "    st.pyplot(fig)\n",
    "\n",
    "\n",
    "    # --- Part 3: Top Journals ---\n",
    "    st.header(\"2. Top Publishing Journals\")\n",
    "    top_n = st.slider(\"Select number of top journals to display\", min_value=5, max_value=30, value=10)\n",
    "    \n",
    "    top_journals = analyze_top_journals(filtered_df, top_n=top_n)\n",
    "    \n",
    "    col1, col2 = st.columns([2, 3])\n",
    "    \n",
    "    with col1:\n",
    "        st.dataframe(top_journals, hide_index=True, use_container_width=True)\n",
    "        \n",
    "    with col2:\n",
    "        fig, ax = plt.subplots(figsize=(12, 6))\n",
    "        sns.barplot(x='Count', y='Journal', data=top_journals, palette='viridis', ax=ax)\n",
    "        ax.set_title(f'Top {top_n} Journals by Publication Count', fontsize=16)\n",
    "        ax.set_xlabel('Number of Papers')\n",
    "        ax.set_ylabel('Journal Name')\n",
    "        plt.tight_layout()\n",
    "        st.pyplot(fig)\n",
    "\n",
    "\n",
    "    # --- Part 3: Word Cloud from Titles ---\n",
    "    st.header(\"3. Most Frequent Title Keywords\")\n",
    "    \n",
    "    word_counts = get_word_frequencies(filtered_df, 'title', top_n=100)\n",
    "    word_freq_dict = {word: count for word, count in word_counts}\n",
    "    \n",
    "    col_wc, col_freq = st.columns(2)\n",
    "    \n",
    "    with col_wc:\n",
    "        # Generate Word Cloud\n",
    "        if word_freq_dict:\n",
    "            wordcloud = WordCloud(\n",
    "                width=800, \n",
    "                height=400, \n",
    "                background_color='white', \n",
    "                colormap='plasma'\n",
    "            ).generate_from_frequencies(word_freq_dict)\n",
    "            \n",
    "            fig, ax = plt.subplots(figsize=(10, 5))\n",
    "            ax.imshow(wordcloud, interpolation='bilinear')\n",
    "            ax.axis('off')\n",
    "            ax.set_title('Word Cloud of Paper Titles', fontsize=16)\n",
    "            st.pyplot(fig)\n",
    "        else:\n",
    "            st.warning(\"Not enough data to generate a meaningful word cloud.\")\n",
    "\n",
    "    with col_freq:\n",
    "        # Display Top Word Frequencies as a table\n",
    "        top_words_df = pd.DataFrame(word_counts, columns=['Word', 'Frequency'])\n",
    "        st.subheader(f\"Top {len(top_words_df)} Keywords in Titles\")\n",
    "        st.dataframe(top_words_df, hide_index=True, use_container_width=True)\n",
    "\n",
    "    \n",
    "    # --- Part 4: Data Sample and Exploration ---\n",
    "    st.header(\"4. Data Examination\")\n",
    "\n",
    "    # Display data structure and sample\n",
    "    with st.expander(\"Examine Data Structure and Sample\"):\n",
    "        st.subheader(\"Data Dimensions & Types (Part 1)\")\n",
    "        st.markdown(f\"**Shape:** {df.shape[0]} rows, {df.shape[1]} columns\")\n",
    "        \n",
    "        st.markdown(\"---\")\n",
    "        \n",
    "        st.subheader(\"Data Types (Part 1)\")\n",
    "        st.dataframe(df.dtypes.reset_index().rename(columns={'index': 'Column', 0: 'Data Type'}), hide_index=True)\n",
    "        \n",
    "        st.markdown(\"---\")\n",
    "\n",
    "        st.subheader(\"Missing Values Check (Part 1)\")\n",
    "        missing_df = df.isnull().sum().reset_index().rename(columns={'index': 'Column', 0: 'Missing Count'})\n",
    "        missing_df['Missing %'] = (missing_df['Missing Count'] / len(df) * 100).round(2)\n",
    "        st.dataframe(missing_df.sort_values('Missing Count', ascending=False), hide_index=True, use_container_width=True)\n",
    "\n",
    "        st.markdown(\"---\")\n",
    "        \n",
    "        st.subheader(\"Statistical Summary of Numerical Columns (Part 1)\")\n",
    "        try:\n",
    "            st.dataframe(df[['abstract_word_count', 'publication_year']].describe().T)\n",
    "        except:\n",
    "             st.warning(\"Numerical columns not found in this filtered view.\")\n",
    "        \n",
    "        st.markdown(\"---\")\n",
    "\n",
    "        st.subheader(\"Filtered Data Sample (First 10 Rows)\")\n",
    "        st.dataframe(filtered_df.head(10), use_container_width=True)\n",
    "    \n",
    "\n",
    "# Run the main Streamlit application\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
